---
- name: Installing Filebeat
  hosts: webservers
  become: true
  tasks:

  - name: Downloading Filebeat
    command:
      curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-amd64.deb

  - name: Install Filebeat
    command:
      sudo dpkg -i filebeat-7.6.1-amd64.deb

  - name: Copy Config
    copy:
      src: /etc/ansible/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml

  - name: enable and configure system module
    command: sudo filebeat modules enable system

  - name: setup filebeat
    command: sudo filebeat setup

  - name: start filebeat service
    command: service filebeat start

  - name: enable service filebeat on boot
    systemd:
      name: filebeat
      enabled: yes